import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Tipbar from "./components/Tipbar";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto">
          <Tipbar 
            text="Acompanhe as melhores promoções disponíveis aqueina Maeztra"
            className="flex justify-center bg-black text-sm py-1 text-white"
            />
          <Navbar />
            {children}
        </div>
      </body>
    </html>
  );
}
